# Generated by Django 4.2.5 on 2024-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(max_length=50),
        ),
    ]
