# Generated by Django 4.2.5 on 2024-01-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
